# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sam.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from  PyQt5.QtMultimedia import QMediaContent, QMediaPlayer
from PyQt5.QtMultimediaWidgets import QVideoWidget
from PyQt5.QtWidgets import QFileDialog
import sys


class Ui_MainWindow(object):
    def setupUi(self, main_window):
        main_window.setObjectName("MainWindow")
        main_window.resize(596, 700)
        main_window.setFixedSize(596, 700)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(500, 10, 91, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.controlWidget = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.controlWidget.setContentsMargins(0, 0, 0, 0)
        self.controlWidget.setObjectName("controlWidget")
        self.muteButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.muteButton.setObjectName("muteButton")
        self.controlWidget.addWidget(self.muteButton, 4, 0, 1, 1)
        self.play_pauseButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.play_pauseButton.setObjectName("play_pauseButton")
        self.controlWidget.addWidget(self.play_pauseButton, 1, 0, 1, 1)
        self.repeatButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.repeatButton.setObjectName("repeatButton")
        self.controlWidget.addWidget(self.repeatButton, 3, 0, 1, 1)
        self.stopButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.stopButton.setObjectName("stopButton")
        self.controlWidget.addWidget(self.stopButton, 2, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 471, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.videoLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.videoLayout.setContentsMargins(0, 0, 0, 0)
        self.videoLayout.setObjectName("videoLayout")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 500, 160, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadMusicButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.loadMusicButton.setObjectName("loadMusicButton")
        self.horizontalLayout.addWidget(self.loadMusicButton)
        self.addPlaylistButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.addPlaylistButton.setObjectName("addPlaylistButton")
        self.horizontalLayout.addWidget(self.addPlaylistButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(500, 380, 91, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.dialLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.dialLayout.setContentsMargins(0, 0, 0, 0)
        self.dialLayout.setObjectName("dialLayout")
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget_2)
        self.widget.setObjectName("widget")
        self.dial = QtWidgets.QDial(self.widget)
        self.dial.setGeometry(QtCore.QRect(20, 130, 50, 64))
        self.dial.setObjectName("dial")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 20))
        self.label.setObjectName("label")
        self.dial_2 = QtWidgets.QDial(self.widget)
        self.dial_2.setGeometry(QtCore.QRect(10, 40, 71, 64))
        self.dial_2.setObjectName("dial_2")
        self.dialLayout.addWidget(self.widget)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 430, 471, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.state = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.state.setObjectName("state")
        self.horizontalLayout_2.addWidget(self.state)
        self.horizontalSlider = QtWidgets.QSlider(self.horizontalLayoutWidget_2)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_2.addWidget(self.horizontalSlider)
        spacerItem = QtWidgets.QSpacerItem(30, 0, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setEnabled(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 596, 21))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.mediaPlayer = QMediaPlayer(None, QMediaPlayer.VideoSurface)
        self.videoWidget = QVideoWidget()
        self.videoLayout.addWidget(self.videoWidget)
        self.mediaPlayer.setVideoOutput(self.videoWidget)
        self.loadMusicButton.clicked.connect(self.load_file)
        self.play_pauseButton.clicked.connect(self.play_video)
        self.stopButton.clicked.connect(self.stop_video)
        self.retranslateui(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def load_file(self):
        filename, _ = QFileDialog.getOpenFileName()

        if filename != "":
            self.mediaPlayer.setMedia(QMediaContent(QtCore.QUrl.fromLocalFile(filename)))
            self.state.setText("Stopped")

    def play_video(self):
        if self.mediaPlayer.state() == 1:
            self.mediaPlayer.pause()
            self.state.setText("Paused")
        elif self.mediaPlayer.state() == 2:
            self.mediaPlayer.play()
            self.state.setText("Playing")
        else:
            self.mediaPlayer.play()
            if self.mediaPlayer.state() == 1:
                self.state.setText("Playing")

    def stop_video(self):
        self.mediaPlayer.stop()
        self.state.setText("Stopped")

    def retranslateui(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.muteButton.setText(_translate("MainWindow", "mute"))
        self.play_pauseButton.setText(_translate("MainWindow", "play/pause"))
        self.repeatButton.setText(_translate("MainWindow", "repeat"))
        self.stopButton.setText(_translate("MainWindow", "stop"))
        self.loadMusicButton.setText(_translate("MainWindow", "load music"))
        self.addPlaylistButton.setText(_translate("MainWindow", "add playlist"))
        self.label.setText(_translate("MainWindow", "Volume"))
        self.state.setText(_translate("MainWindow", "Stopped"))
        self.label_3.setText(_translate("MainWindow", "time"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())